apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: esd-monitoring-dashboard
  description: FrontEnd Dashboard for IoT Monitoring Service
  tags:
    - development
    - frontend
    - team-a 
spec:
  type: service
  lifecycle: development
  owner: rahul-team
