version: '3.3'

services:

  #Mongo_db
  mongo:
      image: mongo
      container_name: mongo
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=rootuser
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
      volumes:
        - ./data:/data/db


  #Webhook Node API

  webhook_api:
    container_name: webhook
    build: ./webhook/
    ports: 
      - 8888:8888
    environment:
       PORT: 8888
       url: 'mongodb://mongo:27017'
       MONGO_ADMIN: admin
       MONGO_USER: rootuser
       MONGO_PASS: rootpass
       MONGO_SERVER: mongo
       MONGO_PORT: 27017
       method: 'cloud'
    restart: always
    external_links:
     - mongo

  dashboard:
    container_name: dashboard
    build: .
    ports:
      - 8889:8080
    restart: always

volumes:
  mongodb-data:
    driver: local

