version: '3.9'

services:

  #Mongo_db
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_db:/data/db
    restart: always
  #Mongo-express service

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  

  #Webhook Node API

  webhook_api:
    container_name: webhook
    build: ./webhook
    ports: 
      - 8888:8888
    environment:
       PORT: 8888
      #  url: 'mongodb://mongodb:27017'
       MONGO_ADMIN: admin
       MONGO_PASS: password
       MONGO_SERVER: mongodb
       MONGO_PORT: 27017
    restart: always
    depends_on:
      - mongodb



volumes: 
 mongo_db: {}

